### ISSUE TITLE
Unittests for auth-server?

### ISSUE THREAD

**Issue by makorne** [Atheer2104/chat-grpc#3]
Hi! 
Thank you for your interesting crates!

But how do you start unittests for  auth-server?

cargo test --color=always --bin auth-server

`test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s`

cargo test --lib -- --list

```
Running unittests src/lib.rs (chat-grpc/target/debug/deps/auth-24863828a93cbefb)
server::validation::types::email::tests::email_missing_at_symbol_is_rejected: test
server::validation::types::email::tests::email_no_subject_is_rejected: test
server::validation::types::email::tests::empty_string_is_rejected: test
server::validation::types::email::tests::valid_emails_are_parsed_successfully: test
server::validation::types::firstname::tests::a_255_grapheme_name_is_parsed: test
server::validation::types::firstname::tests::a_empty_firstname_is_rejected: test
server::validation::types::firstname::tests::a_whitespace_only_firstname_is_rejected: test
server::validation::types::firstname::tests::firstname_consist_of_numbers_only_is_rejected: test
server::validation::types::firstname::tests::firstname_contains_numbers_is_rejected: test
server::validation::types::firstname::tests::firstname_longer_than_255_grapeheme_is_rejected: test
server::validation::types::firstname::tests::valid_firstname_is_parsed: test
server::validation::types::lastname::tests::a_255_grapheme_name_is_parsed: test
server::validation::types::lastname::tests::a_empty_lastname_is_rejected: test
server::validation::types::lastname::tests::a_whitespace_only_lastname_is_rejected: test
server::validation::types::lastname::tests::lastname_consist_of_numbers_only_is_rejected: test
server::validation::types::lastname::tests::lastname_contains_numbers_is_rejected: test
server::validation::types::lastname::tests::lastname_longer_than_255_grapeheme_is_rejected: test
server::validation::types::lastname::tests::valid_lastname_is_parsed: test
server::validation::types::password::tests::a_255_grapheme_password_is_parsed: test
server::validation::types::password::tests::empty_password_is_rejected: test
server::validation::types::password::tests::password_longer_than_255_grapehemes_is_rejected: test
server::validation::types::password::tests::valid_password_is_parsed: test
server::validation::types::password::tests::whitespace_only_password_is_rejected: test
server::validation::types::username::tests::a_255_grapheme_long_username_is_valid: test
server::validation::types::username::tests::a_username_longer_than_255_graphemes_is_rejected: test
server::validation::types::username::tests::a_valid_username_is_parsed_successfully: test
server::validation::types::username::tests::empty_username_is_rejected: test
server::validation::types::username::tests::username_containing_a_forbidden_character: test
server::validation::types::username::tests::whitespace_only_username_is_rejected: test

29 tests, 0 benchmarks  //   All tests for chat server only
```

cargo test --bin auth-server -- --list

```
Running unittests src/bin/server.rs (chat-grpc/target/debug/deps/auth_server-22599d13ee860ee9)
0 tests, 0 benchmarks
```

Thank you!

**Comment by Atheer2104** [comment]
Hello and thank you for taking interest in the repo. 

In order to run the test you have make sure that a redis and postgres instance is running on your machine, this can easily be achieved by running the bash scripts **init_db.sh** and **init_redis.sh**  (they use docker to setup a local instance, so make sure docker is installed on your machine). Note it's important that you execute the script from the root of the project folder , for instance like this `./auth/scripts/init_db.sh`

**prerequisites for init_db.sh**
There are some further prerequisites that are need for running **init_db.sh**

- The script internally uses **psql** command to make sure the db is up, so make sure it's installed on your machine
- **sqlx** command is used to run the migrations, you can download it via cargo using the following [link](https://crates.io/crates/sqlx-cli)

After the instances for PostgreSQL and Redis are up and running use the following command to run the tests `cargo test -- --test-threads=1` in **/auth**

# Extra Clarification on the testing procedure 

There is unit tests which is what you are seeing when running `cargo test --lib -- --list` but there is also integration tests which is in a separate folder called  **tests** in **/auth**. The command I provided above it will actually run 1 test at a time by default rust runs multiple tests at the same time, there was issues with flakey test if one runs multiple integration tests at the same time hence we only run 1 test at a time.


 Feel free to ask me anything :)

**Comment by makorne** [comment]
Excellent work!
